# Bans

BanReasonOne: "Cheating"
BanReasonTwo: "Bug Abuse"
BanReasonThree: "Teaming"
BanReasonFour: "Trolling"
BanReasonFive: "Inappropriate Build"
BanReasonSix: "Inappropriate Items"
BanReasonSeven: "Extreme Disrespect"
BanReasonEight: "Inappropriate Skin"
BanReasonNine: "Boosting"
BanReasonTen: "Profile Boosting"
BanReasonEleven: "Inappropriate Name"
BanReasonTwelve: "Security Alert"
BanReasonThirteen: "Chargeback"
BanReasonFourteen: "Fraud"
BanReasonFifteen: "Unauthorized Pay"
BanReasonSixteen: "Macroing"
BanReasonSeventeen: "Cheating 1st"
BanReasonEighteen: "Cheating 2nd"
BanReasonNinteen: "Cheating 3rd"
BanReasonTwenty: "Cheating 4th"

BanDurationOne: "30d"
BanDurationTwo: "14d"
BanDurationThree: "1h"
BanDurationFour: "1d"
BanDurationFive: "7d"
BanDurationSix: "7d"
BanDurationSeven: "30d"
BanDurationEight: ""
BanDurationNine: "30d"
BanDurationTen: "30d"
BanDurationEleven: ""
BanDurationTwelve: ""
BanDurationThirteen: ""
BanDurationFourteen: ""
BanDurationFifteen: ""
BanDurationSixteen: "30d"
BanDurationSeventeen: "7d"
BanDurationEighteen: "14d"
BanDurationNinteen: "30d"
BanDurationTwenty: ""


# Mutes

MuteReasonOne: ""
MuteReasonTwo: ""
MuteReasonThree: ""
MuteReasonFour: ""
MuteReasonFive: ""
MuteReasonSix: ""
MuteReasonSeven: ""
MuteReasonEight: ""
MuteReasonNine: ""
MuteReasonTen: ""
MuteReasonEleven: ""
MuteReasonTwelve: ""
MuteReasonThirteen: ""
MuteReasonFourteen: ""
MuteReasonFifteen: ""
MuteReasonSixteen: ""
MuteReasonSeventeen: ""
MuteReasonEighteen: ""
MuteReasonNinteen: ""
MuteReasonTwenty: ""

MuteDurationOne: ""
MuteDurationTwo: ""
MuteDurationThree: ""
MuteDurationFour: ""
MuteDurationFive: ""
MuteDurationSix: ""
MuteDurationSeven: ""
MuteDurationEight: ""
MuteDurationNine: ""
MuteDurationTen: ""
MuteDurationEleven: ""
MuteDurationTwelve: ""
MuteDurationThirteen: ""
MuteDurationFourteen: ""
MuteDurationFifteen: ""
MuteDurationSixteen: ""
MuteDurationSeventeen: ""
MuteDurationEighteen: ""
MuteDurationNinteen: ""
MuteDurationTwenty: ""


# Warns

WarnReasonOne: ""
WarnReasonTwo: ""
WarnReasonThree: ""
WarnReasonFour: ""
WarnReasonFive: ""
WarnReasonSix: ""
WarnReasonSeven: ""
WarnReasonEight: ""
WarnReasonNine: ""
WarnReasonTen: ""
WarnReasonEleven: ""
WarnReasonTwelve: ""
WarnReasonThirteen: ""
WarnReasonFourteen: ""
WarnReasonFifteen: ""
WarnReasonSixteen: ""
WarnReasonSeventeen: ""
WarnReasonEighteen: ""
WarnReasonNinteen: ""
WarnReasonTwenty: ""


# Kicks

KickReasonOne: ""
KickReasonTwo: ""
KickReasonThree: ""
KickReasonFour: ""
KickReasonFive: ""
KickReasonSix: ""
KickReasonSeven: ""
KickReasonEight: ""
KickReasonNine: ""
KickReasonTen: ""
KickReasonEleven: ""
KickReasonTwelve: ""
KickReasonThirteen: ""
KickReasonFourteen: ""
KickReasonFifteen: ""
KickReasonSixteen: ""
KickReasonSeventeen: ""
KickReasonEighteen: ""
KickReasonNinteen: ""
KickReasonTwenty: ""
